# Generated by Django 5.2.5 on 2025-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(related_name="messages", to="messenger.tag"),
        ),
    ]
