# Generated by Django 5.2.5 on 2025-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_message_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
