# Generated by Django 5.2.5 on 2025-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
